name: flutterbasesource
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.1.3
  http: ^0.12.0+4
  connectivity: ^0.4.8+2
  flutter_local_notifications: ^1.4.4+1
  shared_preferences: ^0.5.6+1
  flutter_secure_storage: 3.3.5
  device_info: ^0.4.1+5
  get_ip: ^0.4.0
  flutter_ip: ^0.2.0
  crypto: ^2.1.3
  permission_handler: ^5.0.0+hotfix.3
  device_preview: ^0.4.5
  new_version: ^0.0.5
  launch_review: ^2.0.0
  month_picker_dialog: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - language/
    - assets/images/
